### ISSUE TITLE
about the paper

### ISSUE THREAD

**Issue by dumyy** [Likekekeke/EasyGaze3D#1]
hi, I wonder when the paper is published?  It seems that the paper can't be found by searching the title "easygaze3d".

**Comment by Likekekeke** [comment]
Hi, the paper has not been published yet, and welcome for any questions :)

**Comment by Likekekeke** [comment]
Hi, thanks for your interest.

The paper will be published in around September 2023, and welcome for any questions :)

**Comment by dumyy** [comment]
i see it, thank you
