### ISSUE TITLE
About the "gaze_C"?

### ISSUE THREAD

**Issue by Echo-jyt** [Likekekeke/EasyGaze3D#3]
Hi, thanks for your work! What is the meaning of "gaze_C" in the demo_webcam.py? I would be very grateful if you could answer me!

**Comment by Likekekeke** [comment]
Hi, "gaze_C" means the gaze vector in the Camera-Coordinate-System (CCS), which is the aim for this "Gaze Estimation" task. Similarly, "gaze_W" is the gaze vector in the World-Coordinate-System (WCS). Note that the WCS here is fixed with the user's face.

**Comment by Echo-jyt** [comment]
> Hi, "gaze_C" means the gaze vector in the Camera-Coordinate-System (CCS), which is the aim for this "Gaze Estimation" task. Similarly, "gaze_W" is the gaze vector in the World-Coordinate-System (WCS). Note that the WCS here is fixed with the user's face.

Thank you so much!
