### ISSUE TITLE
关于眼球中心的问题

### ISSUE THREAD

**Issue by Echo-jyt** [Likekekeke/EasyGaze3D#4]
您好，请问为什么代码里面只计算出了一份眼球中心的位置呢？在eyeball_center.npy

**Comment by Likekekeke** [comment]
您好，这里的眼球中心是标定算法的输出结果之一，是定义在世界坐标系（WCS）中的左右眼球中心坐标。就像之前说的，此处的世界坐标系是与面部固定的坐标系，眼球中心在此坐标系中的坐标是一个固定值，不受头部姿态和眼球转动等因素影响。

**Comment by Echo-jyt** [comment]
> 您好，这里的眼球中心是标定算法的输出结果之一，是定义在世界坐标系（WCS）中的左右眼球中心坐标。就像之前说的，此处的世界坐标系是与面部固定的坐标系，眼球中心在此坐标系中的坐标是一个固定值，不受头部姿态和眼球转动等因素影响。

您好，请问我是否可以这样理解，眼球中心是和人头一起运动的（相对静止），所以眼球中心在人脸这个世界坐标系里的坐标是一个固定值？

**Comment by Likekekeke** [comment]
> > 您好，这里的眼球中心是标定算法的输出结果之一，是定义在世界坐标系（WCS）中的左右眼球中心坐标。就像之前说的，此处的世界坐标系是与面部固定的坐标系，眼球中心在此坐标系中的坐标是一个固定值，不受头部姿态和眼球转动等因素影响。
> 
> 您好，请问我是否可以这样理解，眼球中心是和人头一起运动的（相对静止），所以眼球中心在人脸这个世界坐标系里的坐标是一个固定值？

是的。

**Comment by Echo-jyt** [comment]
> > > 您好，这里的眼球中心是标定算法的输出结果之一，是定义在世界坐标系（WCS）中的左右眼球中心坐标。就像之前说的，此处的世界坐标系是与面部固定的坐标系，眼球中心在此坐标系中的坐标是一个固定值，不受头部姿态和眼球转动等因素影响。
> > 
> > 
> > 您好，请问我是否可以这样理解，眼球中心是和人头一起运动的（相对静止），所以眼球中心在人脸这个世界坐标系里的坐标是一个固定值？
> 
> 是的。

谢谢！
